import { pgTable, uuid, text, timestamp, numeric, integer, bigint, bigserial, boolean, date, jsonb, index, uniqueIndex, primaryKey } from 'drizzle-orm/pg-core';

const id = () => uuid('id').primaryKey().defaultRandom();
const tz = (name: string) => timestamp(name, { withTimezone: true });
const created = () => tz('created_at').notNull().defaultNow();
const money = (name: string) => numeric(name, { precision: 18, scale: 2 }).notNull().default('0');
const qty = (name: string) => numeric(name, { precision: 18, scale: 3 }).notNull().default('0');
// Оптимистическая блокировка (§4.1): каждое изменение строки увеличивает version.
const versioned = () => ({ version: integer('version').notNull().default(1), updatedAt: tz('updated_at').notNull().defaultNow() });
// Происхождение факта (§4.1): где, когда и кем введено, когда принято сервером.
const provenance = () => ({ origin: text('origin').notNull().default('online'), deviceId: uuid('device_id'), deviceCreatedAt: tz('device_created_at'), serverReceivedAt: tz('server_received_at').notNull().defaultNow(), opId: uuid('op_id') });

export const organizations = pgTable('organizations', { id: id(), name: text('name').notNull(), inn: text('inn'), createdAt: created() });
export const users = pgTable('users', { id: id(), organizationId: uuid('organization_id').references(() => organizations.id).notNull(), name: text('name').notNull(), email: text('email').notNull(), passwordHash: text('password_hash').notNull(), role: text('role').notNull().default('read_only'), isActive: boolean('is_active').notNull().default(true), sessionVersion: integer('session_version').notNull().default(1), mustChangePassword: boolean('must_change_password').notNull().default(false), passwordChangedAt: tz('password_changed_at'), createdAt: created() }, t => [uniqueIndex('users_email_unique').on(t.email)]);
export const projectAccess = pgTable('project_access', { id: id(), userId: uuid('user_id').references(() => users.id).notNull(), projectId: uuid('project_id').references(() => projects.id).notNull(), permission: text('permission').notNull().default('view') }, t => [uniqueIndex('project_access_unique').on(t.userId,t.projectId)]);
export const counterparties = pgTable('counterparties', { id: id(), organizationId: uuid('organization_id').references(() => organizations.id).notNull(), name: text('name').notNull(), kind: text('kind').notNull().default('supplier'), inn: text('inn'), contact: text('contact'), createdAt: created(), ...versioned() });
export const projects = pgTable('projects', { id: id(), organizationId: uuid('organization_id').references(() => organizations.id).notNull(), code: text('code').notNull(), name: text('name').notNull(), address: text('address'), customerId: uuid('customer_id').references(() => counterparties.id), managerId: uuid('manager_id').references(() => users.id), status: text('status').notNull().default('active'), startDate: date('start_date'), endDate: date('end_date'), progress: integer('progress').notNull().default(0), contractValue: money('contract_value'), forecast: money('forecast'), description: text('description'), createdAt: created(), ...versioned() }, t => [uniqueIndex('projects_org_code').on(t.organizationId,t.code), index('projects_org_idx').on(t.organizationId)]);
export const contracts = pgTable('contracts', { id: id(), organizationId: uuid('organization_id').references(() => organizations.id).notNull(), projectId: uuid('project_id').references(() => projects.id), counterpartyId: uuid('counterparty_id').references(() => counterparties.id).notNull(), number: text('number').notNull(), kind: text('kind').notNull(), amount: money('amount'), signedAt: date('signed_at'), dueAt: date('due_at'), status: text('status').notNull().default('active'), createdAt: created(), ...versioned() });
export const tasks = pgTable('tasks', { id: id(), projectId: uuid('project_id').references(() => projects.id).notNull(), parentId: uuid('parent_id'), code: text('code'), name: text('name').notNull(), kind: text('kind').notNull().default('work'), assigneeId: uuid('assignee_id').references(() => users.id), startDate: date('start_date'), endDate: date('end_date'), actualEnd: date('actual_end'), progress: integer('progress').notNull().default(0), plannedCost: money('planned_cost'), actualQuantity: qty('actual_quantity'), unit: text('unit').notNull().default('шт'), status: text('status').notNull().default('planned'),
  // Время (по устройству) факта, давшего текущее значение progress; более ранние факты остаются только в истории.
  progressReportedAt: tz('progress_reported_at'), createdAt: created(), ...versioned() }, t => [index('tasks_project_idx').on(t.projectId)]);
export const taskDependencies = pgTable('task_dependencies', { id: id(), taskId: uuid('task_id').references(() => tasks.id).notNull(), predecessorId: uuid('predecessor_id').references(() => tasks.id).notNull(), type: text('type').notNull().default('FS'), lagDays: integer('lag_days').notNull().default(0) });
export const budgetLines = pgTable('budget_lines', { id: id(), projectId: uuid('project_id').references(() => projects.id).notNull(), taskId: uuid('task_id').references(() => tasks.id), category: text('category').notNull(), period: text('period'), amount: money('amount'), note: text('note'), createdAt: created(), ...versioned() }, t => [index('budget_project_idx').on(t.projectId)]);
export const expenses = pgTable('expenses', { id: id(), projectId: uuid('project_id').references(() => projects.id).notNull(), taskId: uuid('task_id').references(() => tasks.id), contractId: uuid('contract_id').references(() => contracts.id), counterpartyId: uuid('counterparty_id').references(() => counterparties.id), category: text('category').notNull(), description: text('description').notNull(), amount: money('amount'), incurredAt: date('incurred_at').notNull(), createdAt: created(), ...provenance() }, t => [index('expenses_project_idx').on(t.projectId)]);
export const materials = pgTable('materials', { id: id(), organizationId: uuid('organization_id').references(() => organizations.id).notNull(), sku: text('sku').notNull(), name: text('name').notNull(), category: text('category'), unit: text('unit').notNull().default('шт'), minStock: qty('min_stock'), price: money('price'), createdAt: created(), ...versioned() }, t => [uniqueIndex('materials_org_sku').on(t.organizationId,t.sku)]);
export const warehouses = pgTable('warehouses', { id: id(), organizationId: uuid('organization_id').references(() => organizations.id).notNull(), projectId: uuid('project_id').references(() => projects.id), name: text('name').notNull(), location: text('location'), ...versioned() });
export const stockMovements = pgTable('stock_movements', { id: id(), materialId: uuid('material_id').references(() => materials.id).notNull(), warehouseId: uuid('warehouse_id').references(() => warehouses.id).notNull(), projectId: uuid('project_id').references(() => projects.id), purchaseId: uuid('purchase_id').references(() => purchases.id), taskId: uuid('task_id').references(() => tasks.id), type: text('type').notNull(), quantity: qty('quantity'), note: text('note'), createdAt: created(), ...provenance() }, t => [index('stock_material_warehouse_idx').on(t.materialId,t.warehouseId)]);
export const purchases = pgTable('purchases', { id: id(), organizationId: uuid('organization_id').references(() => organizations.id).notNull(), projectId: uuid('project_id').references(() => projects.id).notNull(), materialId: uuid('material_id').references(() => materials.id).notNull(), supplierId: uuid('supplier_id').references(() => counterparties.id), warehouseId: uuid('warehouse_id').references(() => warehouses.id), number: text('number').notNull(),
  // Временный номер, присвоенный клиентом офлайн (P4); постоянный number присваивает сервер.
  localRef: text('local_ref'), quantity: qty('quantity'), receivedQuantity: qty('received_quantity'), unitPrice: money('unit_price'), status: text('status').notNull().default('requested'), dueAt: date('due_at'), note: text('note'), createdAt: created(), ...versioned(), ...provenance() }, t => [index('purchases_project_idx').on(t.projectId)]);
export const approvals = pgTable('approvals', { id: id(), organizationId: uuid('organization_id').references(() => organizations.id).notNull(), entityType: text('entity_type').notNull(), entityId: uuid('entity_id').notNull(), step: integer('step').notNull().default(1), status: text('status').notNull().default('pending'), assignedRole: text('assigned_role').notNull().default('director'), comment: text('comment'), decidedBy: uuid('decided_by').references(() => users.id), decidedAt: tz('decided_at'), deadline: date('deadline'), createdAt: created(), ...versioned() });
export const documents = pgTable('documents', { id: id(), organizationId: uuid('organization_id').references(() => organizations.id).notNull(), projectId: uuid('project_id').references(() => projects.id), contractId: uuid('contract_id').references(() => contracts.id), name: text('name').notNull(), category: text('category').notNull().default('other'), fileKey: text('file_key').notNull(), mime: text('mime').notNull(), size: integer('size').notNull(), version: integer('version').notNull().default(1), uploadedBy: uuid('uploaded_by').references(() => users.id), createdAt: created() });
export const notifications = pgTable('notifications', { id: id(), userId: uuid('user_id').references(() => users.id).notNull(), title: text('title').notNull(), body: text('body'), href: text('href'), read: boolean('read').notNull().default(false), createdAt: created() });
export const auditLogs = pgTable('audit_logs', { id: id(), organizationId: uuid('organization_id').references(() => organizations.id).notNull(), actorId: uuid('actor_id').references(() => users.id), action: text('action').notNull(), entityType: text('entity_type').notNull(), entityId: uuid('entity_id'), before: jsonb('before'), after: jsonb('after'), ip: text('ip'), userAgent: text('user_agent'), origin: text('origin').notNull().default('online'), deviceId: uuid('device_id'), deviceCreatedAt: tz('device_created_at'), createdAt: created() }, t => [index('audit_org_date_idx').on(t.organizationId,t.createdAt)]);
// Счётчик неудачных входов по ключу email+ip (общий для всех экземпляров приложения).
export const loginAttempts = pgTable('login_attempts', { key: text('key').primaryKey(), count: integer('count').notNull().default(0), until: tz('until').notNull() });

// История фактов выполнения (§4.1): каждый progress.set — строка; tasks.progress = последний по device_created_at.
export const taskProgressLog = pgTable('task_progress_log', { id: id(), taskId: uuid('task_id').references(() => tasks.id).notNull(), projectId: uuid('project_id').references(() => projects.id).notNull(), authorId: uuid('author_id').references(() => users.id).notNull(), progress: integer('progress').notNull(), actualQuantity: numeric('actual_quantity', { precision: 18, scale: 3 }),
  // Стал ли факт текущим значением работы (false — пришёл позже более нового факта).
  applied: boolean('applied').notNull(), createdAt: created(), ...provenance() }, t => [index('task_progress_task_idx').on(t.taskId, t.deviceCreatedAt)]);
// Журнал изменений (§4.2): пишется в той же транзакции, что и данные; по нему SSE-сигналы и pull (P3).
export const changeLog = pgTable('change_log', { seq: bigserial('seq', { mode: 'number' }).primaryKey(), organizationId: uuid('organization_id').references(() => organizations.id).notNull(), projectId: uuid('project_id'), entity: text('entity').notNull(), entityId: uuid('entity_id').notNull(), op: text('op').notNull(), changedAt: tz('changed_at').notNull().defaultNow() }, t => [index('change_log_org_seq_idx').on(t.organizationId, t.seq), index('change_log_changed_at_idx').on(t.changedAt)]);
// Идемпотентность (§4.2): результат операции по её ключу (HTTP Idempotency-Key сейчас, op_id sync push в P4).
export const syncOps = pgTable('sync_ops', { opId: uuid('op_id').primaryKey(), deviceId: uuid('device_id'), userId: uuid('user_id').references(() => users.id).notNull(), command: text('command').notNull(), payloadHash: text('payload_hash').notNull(), status: text('status').notNull(), httpStatus: integer('http_status').notNull(), result: jsonb('result'), deviceCreatedAt: tz('device_created_at'), receivedAt: tz('received_at').notNull().defaultNow() });
// Сквозные счётчики организации (номера заявок и т. п.).
export const orgCounters = pgTable('org_counters', { organizationId: uuid('organization_id').references(() => organizations.id).notNull(), name: text('name').notNull(), value: bigint('value', { mode: 'number' }).notNull() }, t => [primaryKey({ columns: [t.organizationId, t.name] })]);
