import { pgTable, uuid, text, timestamp, numeric, integer, boolean, date, jsonb, index, uniqueIndex } from 'drizzle-orm/pg-core';

const id = () => uuid('id').primaryKey().defaultRandom();
const created = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();
const money = (name: string) => numeric(name, { precision: 18, scale: 2 }).notNull().default('0');
const qty = (name: string) => numeric(name, { precision: 18, scale: 3 }).notNull().default('0');

export const organizations = pgTable('organizations', { id: id(), name: text('name').notNull(), inn: text('inn'), createdAt: created() });
export const users = pgTable('users', { id: id(), organizationId: uuid('organization_id').references(() => organizations.id).notNull(), name: text('name').notNull(), email: text('email').notNull(), passwordHash: text('password_hash').notNull(), role: text('role').notNull().default('read_only'), createdAt: created() }, t => [uniqueIndex('users_email_unique').on(t.email)]);
export const projectAccess = pgTable('project_access', { id: id(), userId: uuid('user_id').references(() => users.id).notNull(), projectId: uuid('project_id').references(() => projects.id).notNull(), permission: text('permission').notNull().default('view') }, t => [uniqueIndex('project_access_unique').on(t.userId,t.projectId)]);
export const counterparties = pgTable('counterparties', { id: id(), organizationId: uuid('organization_id').references(() => organizations.id).notNull(), name: text('name').notNull(), kind: text('kind').notNull().default('supplier'), inn: text('inn'), contact: text('contact'), createdAt: created() });
export const projects = pgTable('projects', { id: id(), organizationId: uuid('organization_id').references(() => organizations.id).notNull(), code: text('code').notNull(), name: text('name').notNull(), address: text('address'), customerId: uuid('customer_id').references(() => counterparties.id), managerId: uuid('manager_id').references(() => users.id), status: text('status').notNull().default('active'), startDate: date('start_date'), endDate: date('end_date'), progress: integer('progress').notNull().default(0), contractValue: money('contract_value'), forecast: money('forecast'), description: text('description'), createdAt: created() }, t => [uniqueIndex('projects_org_code').on(t.organizationId,t.code), index('projects_org_idx').on(t.organizationId)]);
export const contracts = pgTable('contracts', { id: id(), organizationId: uuid('organization_id').references(() => organizations.id).notNull(), projectId: uuid('project_id').references(() => projects.id), counterpartyId: uuid('counterparty_id').references(() => counterparties.id).notNull(), number: text('number').notNull(), kind: text('kind').notNull(), amount: money('amount'), signedAt: date('signed_at'), dueAt: date('due_at'), status: text('status').notNull().default('active'), createdAt: created() });
export const tasks = pgTable('tasks', { id: id(), projectId: uuid('project_id').references(() => projects.id).notNull(), parentId: uuid('parent_id'), code: text('code'), name: text('name').notNull(), kind: text('kind').notNull().default('work'), assigneeId: uuid('assignee_id').references(() => users.id), startDate: date('start_date'), endDate: date('end_date'), actualEnd: date('actual_end'), progress: integer('progress').notNull().default(0), plannedCost: money('planned_cost'), actualQuantity: qty('actual_quantity'), unit: text('unit').notNull().default('шт'), status: text('status').notNull().default('planned'), createdAt: created() }, t => [index('tasks_project_idx').on(t.projectId)]);
export const taskDependencies = pgTable('task_dependencies', { id: id(), taskId: uuid('task_id').references(() => tasks.id).notNull(), predecessorId: uuid('predecessor_id').references(() => tasks.id).notNull(), type: text('type').notNull().default('FS'), lagDays: integer('lag_days').notNull().default(0) });
export const budgetLines = pgTable('budget_lines', { id: id(), projectId: uuid('project_id').references(() => projects.id).notNull(), taskId: uuid('task_id').references(() => tasks.id), category: text('category').notNull(), period: text('period'), amount: money('amount'), note: text('note'), createdAt: created() }, t => [index('budget_project_idx').on(t.projectId)]);
export const expenses = pgTable('expenses', { id: id(), projectId: uuid('project_id').references(() => projects.id).notNull(), taskId: uuid('task_id').references(() => tasks.id), contractId: uuid('contract_id').references(() => contracts.id), counterpartyId: uuid('counterparty_id').references(() => counterparties.id), category: text('category').notNull(), description: text('description').notNull(), amount: money('amount'), incurredAt: date('incurred_at').notNull(), createdAt: created() }, t => [index('expenses_project_idx').on(t.projectId)]);
export const materials = pgTable('materials', { id: id(), organizationId: uuid('organization_id').references(() => organizations.id).notNull(), sku: text('sku').notNull(), name: text('name').notNull(), category: text('category'), unit: text('unit').notNull().default('шт'), minStock: qty('min_stock'), price: money('price'), createdAt: created() }, t => [uniqueIndex('materials_org_sku').on(t.organizationId,t.sku)]);
export const warehouses = pgTable('warehouses', { id: id(), organizationId: uuid('organization_id').references(() => organizations.id).notNull(), projectId: uuid('project_id').references(() => projects.id), name: text('name').notNull(), location: text('location') });
export const stockMovements = pgTable('stock_movements', { id: id(), materialId: uuid('material_id').references(() => materials.id).notNull(), warehouseId: uuid('warehouse_id').references(() => warehouses.id).notNull(), projectId: uuid('project_id').references(() => projects.id), purchaseId: uuid('purchase_id').references(() => purchases.id), taskId: uuid('task_id').references(() => tasks.id), type: text('type').notNull(), quantity: qty('quantity'), note: text('note'), createdAt: created() }, t => [index('stock_material_warehouse_idx').on(t.materialId,t.warehouseId)]);
export const purchases = pgTable('purchases', { id: id(), organizationId: uuid('organization_id').references(() => organizations.id).notNull(), projectId: uuid('project_id').references(() => projects.id).notNull(), materialId: uuid('material_id').references(() => materials.id).notNull(), supplierId: uuid('supplier_id').references(() => counterparties.id), warehouseId: uuid('warehouse_id').references(() => warehouses.id), number: text('number').notNull(), quantity: qty('quantity'), receivedQuantity: qty('received_quantity'), unitPrice: money('unit_price'), status: text('status').notNull().default('requested'), dueAt: date('due_at'), note: text('note'), createdAt: created() }, t => [index('purchases_project_idx').on(t.projectId)]);
export const approvals = pgTable('approvals', { id: id(), organizationId: uuid('organization_id').references(() => organizations.id).notNull(), entityType: text('entity_type').notNull(), entityId: uuid('entity_id').notNull(), step: integer('step').notNull().default(1), status: text('status').notNull().default('pending'), assignedRole: text('assigned_role').notNull().default('director'), comment: text('comment'), decidedBy: uuid('decided_by').references(() => users.id), decidedAt: timestamp('decided_at', { withTimezone: true }), deadline: date('deadline'), createdAt: created() });
export const documents = pgTable('documents', { id: id(), organizationId: uuid('organization_id').references(() => organizations.id).notNull(), projectId: uuid('project_id').references(() => projects.id), contractId: uuid('contract_id').references(() => contracts.id), name: text('name').notNull(), category: text('category').notNull().default('other'), fileKey: text('file_key').notNull(), mime: text('mime').notNull(), size: integer('size').notNull(), version: integer('version').notNull().default(1), uploadedBy: uuid('uploaded_by').references(() => users.id), createdAt: created() });
export const notifications = pgTable('notifications', { id: id(), userId: uuid('user_id').references(() => users.id).notNull(), title: text('title').notNull(), body: text('body'), href: text('href'), read: boolean('read').notNull().default(false), createdAt: created() });
export const auditLogs = pgTable('audit_logs', { id: id(), organizationId: uuid('organization_id').references(() => organizations.id).notNull(), actorId: uuid('actor_id').references(() => users.id), action: text('action').notNull(), entityType: text('entity_type').notNull(), entityId: uuid('entity_id'), before: jsonb('before'), after: jsonb('after'), ip: text('ip'), userAgent: text('user_agent'), createdAt: created() }, t => [index('audit_org_date_idx').on(t.organizationId,t.createdAt)]);
