import { NextRequest } from 'next/server';
import { db } from '@/db';
import { organizations, projects, projectAccess, tasks, budgetLines, expenses, materials, warehouses, stockMovements, purchases, counterparties, contracts, approvals, auditLogs, notifications } from '@/db/schema';
import { currentUser, writeRoles } from '@/lib/session';
import { getOverview } from '@/lib/overview';
import { eq, and, sql } from 'drizzle-orm';
import { z, ZodError } from 'zod';

export const dynamic = 'force-dynamic';
const uuid = z.string().uuid(); const amount = z.string().regex(/^(?!0+(?:\.0{1,2})?$)\d{1,16}(?:\.\d{1,2})?$/, 'Укажите положительную сумму с точностью до копеек'); const quantity = z.coerce.number().positive().finite();
const schemas = {
  organizations: z.object({ name: z.string().min(2), inn: z.string().optional() }),
  projects: z.object({ name: z.string().min(2), code: z.string().min(2), address: z.string().optional(), contractValue: amount.optional(), forecast: amount.optional(), endDate: z.string().optional(), description: z.string().optional() }),
  tasks: z.object({ projectId: uuid, name: z.string().min(2), kind: z.enum(['stage','section','work','subtask']).default('work'), parentId: uuid.optional(), startDate: z.string().optional(), endDate: z.string().optional(), plannedCost: amount.optional(), unit: z.string().optional() }),
  budgets: z.object({ projectId: uuid, category: z.string().min(2), amount, taskId: uuid.optional(), period: z.string().optional() }),
  expenses: z.object({ projectId: uuid, category: z.string().min(2), description: z.string().min(2), amount, taskId: uuid.optional(), contractId: uuid.optional(), counterpartyId: uuid.optional(), incurredAt: z.string().optional() }),
  materials: z.object({ name: z.string().min(2), sku: z.string().min(2), unit: z.string().min(1), category: z.string().optional(), minStock: z.coerce.number().min(0).optional(), price: z.string().regex(/^\d{1,16}(?:\.\d{1,2})?$/).optional() }),
  warehouses: z.object({ name: z.string().min(2), projectId: uuid.optional(), location: z.string().optional() }),
  suppliers: z.object({ name: z.string().min(2), inn: z.string().optional(), contact: z.string().optional(), kind: z.enum(['supplier','customer','contractor']).default('supplier') }),
  contracts: z.object({ number: z.string().min(2), projectId: uuid.optional(), counterpartyId: uuid, kind: z.string().min(2), amount, signedAt: z.string().optional() }),
  purchases: z.object({ projectId: uuid, materialId: uuid, warehouseId: uuid.optional(), supplierId: uuid.optional(), quantity, unitPrice: z.string().regex(/^\d{1,16}(?:\.\d{1,2})?$/), dueAt: z.string().optional(), note: z.string().optional() }),
  movements: z.object({ materialId: uuid, warehouseId: uuid, projectId: uuid.optional(), taskId: uuid.optional(), quantity, type: z.enum(['receipt','issue','return','writeoff']), note: z.string().optional() }),
  approvals: z.object({ purchaseId: uuid, decision: z.enum(['approve','reject','return']), comment: z.string().optional() }),
  receive: z.object({ purchaseId: uuid, quantity, warehouseId: uuid.optional() }),
  progress: z.object({ taskId: uuid, progress: z.coerce.number().int().min(0).max(100), actualQuantity: z.coerce.number().min(0).optional() })
};
const tables = { organizations, projects, tasks, budgets: budgetLines, expenses, materials, warehouses, suppliers: counterparties, contracts, purchases, movements: stockMovements, approvals };
function error(message: string, status = 400) { return Response.json({ error: { message } }, { status }); }
function audit(tx: Parameters<Parameters<typeof db.transaction>[0]>[0], user: NonNullable<Awaited<ReturnType<typeof currentUser>>>, req: NextRequest, action: string, type: string, id: string, before: unknown, after: unknown) {
  return tx.insert(auditLogs).values({ organizationId: user.organizationId, actorId: user.id, action, entityType: type, entityId: id, before, after, ip: req.headers.get('x-forwarded-for')?.split(',')[0] || null, userAgent: req.headers.get('user-agent') });
}
export async function GET(req: NextRequest, { params }: { params: Promise<{resource:string}> }) {
  const { resource } = await params;
  if (resource === 'overview') { if(process.env.ERP_PRIVATE_MODE === 'true' && !await currentUser()) return error('Войдите в систему',401); try { return Response.json(await getOverview()); } catch { return error('Данные пока недоступны. Примените схему БД и загрузите демонстрационные данные.',503); } }
  if (!(resource in tables)) return error('Ресурс не найден',404);
  const user = await currentUser(); if (!user) return error('Войдите в систему',401);
  const data = await getOverview();
  const key = resource === 'suppliers' ? 'counterparties' : resource === 'budgets' ? 'budgets' : resource === 'movements' ? 'movements' : resource;
  const items = (data as unknown as Record<string, unknown[]>)[key] || [];
  const search = (req.nextUrl.searchParams.get('search') || '').toLowerCase(); const projectId = req.nextUrl.searchParams.get('projectId');
  const filtered = items.filter(x => { const row = x as Record<string,unknown>; return (!search || JSON.stringify(row).toLowerCase().includes(search)) && (!projectId || row.projectId === projectId) && (resource !== 'suppliers' || row.kind === 'supplier'); });
  const page = Math.max(1,Number(req.nextUrl.searchParams.get('page')) || 1), limit = Math.min(100,Math.max(1,Number(req.nextUrl.searchParams.get('limit')) || 20));
  return Response.json({ data: filtered.slice((page-1)*limit,page*limit), total: filtered.length, page, limit });
}
export async function POST(req: NextRequest, { params }: { params: Promise<{resource:string}> }) {
  const { resource } = await params;
  const origin = req.headers.get('origin'); if(origin && origin !== req.nextUrl.origin) return error('Недопустимый источник запроса',403);
  const user = await currentUser(); if (!user) return error('Войдите в систему',401);
  if (!writeRoles.includes(user.role)) return error('Недостаточно прав для изменения данных',403);
  if (!(resource in schemas)) return error('Ресурс не найден',404);
  try {
    const input = schemas[resource as keyof typeof schemas].parse(await req.json()) as Record<string, any>;
    const restricted = ['approvals','receive'].includes(resource) && !['director','super_admin','project_manager','procurement_manager'].includes(user.role);
    if (restricted) return error('Недостаточно прав для согласования или приемки',403);
    const result = await db.transaction(async tx => {
      if (input.projectId) { const [p] = await tx.select().from(projects).where(and(eq(projects.id,input.projectId),eq(projects.organizationId,user.organizationId))); if (!p) throw new Error('Объект не найден или нет доступа'); if(!['director','super_admin'].includes(user.role)){const [access]=await tx.select().from(projectAccess).where(and(eq(projectAccess.projectId,p.id),eq(projectAccess.userId,user.id))); if(!access || access.permission==='view') throw new Error('Недостаточно прав на этот объект');} }
      if (resource === 'organizations') { if (user.role !== 'super_admin') throw new Error('Недостаточно прав'); const [row] = await tx.insert(organizations).values({name:input.name,inn:input.inn}).returning(); await audit(tx,user,req,'create','organization',row.id,null,row); return row; }
      if (resource === 'projects') { const [row] = await tx.insert(projects).values({organizationId:user.organizationId,code:input.code,name:input.name,address:input.address,description:input.description,contractValue:String(input.contractValue||0),forecast:String(input.forecast||0),endDate:input.endDate||null,status:'active'}).returning(); await audit(tx,user,req,'create','project',row.id,null,row); return row; }
      if (resource === 'tasks') { const [row] = await tx.insert(tasks).values({projectId:input.projectId,name:input.name,kind:input.kind,parentId:input.parentId||null,startDate:input.startDate||null,endDate:input.endDate||null,plannedCost:String(input.plannedCost||0),unit:input.unit||'шт'}).returning(); await audit(tx,user,req,'create','task',row.id,null,row); return row; }
      if (resource === 'progress') { const [old] = await tx.select().from(tasks).where(eq(tasks.id,input.taskId)); if (!old) throw new Error('Работа не найдена'); const [p] = await tx.select().from(projects).where(and(eq(projects.id,old.projectId),eq(projects.organizationId,user.organizationId))); if (!p) throw new Error('Нет доступа'); const [row] = await tx.update(tasks).set({progress:input.progress,actualQuantity:String(input.actualQuantity||old.actualQuantity),status:input.progress === 100?'done':'active',actualEnd:input.progress === 100 ? new Date().toISOString().slice(0,10) : null}).where(eq(tasks.id,old.id)).returning(); await audit(tx,user,req,'update','task',row.id,old,row); return row; }
      if (resource === 'budgets') { const [row] = await tx.insert(budgetLines).values({projectId:input.projectId,category:input.category,amount:String(input.amount),taskId:input.taskId||null,period:input.period||null}).returning(); await audit(tx,user,req,'create','budget',row.id,null,row); return row; }
      if (resource === 'expenses') { const [row] = await tx.insert(expenses).values({projectId:input.projectId,category:input.category,description:input.description,amount:String(input.amount),taskId:input.taskId||null,contractId:input.contractId||null,counterpartyId:input.counterpartyId||null,incurredAt:input.incurredAt||new Date().toISOString().slice(0,10)}).returning(); await audit(tx,user,req,'create','expense',row.id,null,row); const [totals] = await tx.select({total:sql<string>`coalesce(sum(${expenses.amount}),0)`}).from(expenses).where(eq(expenses.projectId,input.projectId)); const [budget] = await tx.select({total:sql<string>`coalesce(sum(${budgetLines.amount}),0)`}).from(budgetLines).where(eq(budgetLines.projectId,input.projectId)); if(Number(totals.total)>Number(budget.total)) await tx.insert(notifications).values({userId:user.id,title:'Превышен бюджет объекта',body:`Расходы: ${totals.total} ₽; бюджет: ${budget.total} ₽`,href:`/projects/${input.projectId}`}); return { ...row, budgetWarning:Number(totals.total)>Number(budget.total) }; }
      if (resource === 'materials') { const [row] = await tx.insert(materials).values({organizationId:user.organizationId,name:input.name,sku:input.sku,unit:input.unit,category:input.category,minStock:String(input.minStock||0),price:String(input.price||0)}).returning(); await audit(tx,user,req,'create','material',row.id,null,row); return row; }
      if (resource === 'warehouses') { const [row] = await tx.insert(warehouses).values({organizationId:user.organizationId,name:input.name,projectId:input.projectId||null,location:input.location}).returning(); await audit(tx,user,req,'create','warehouse',row.id,null,row); return row; }
      if (resource === 'suppliers') { const [row] = await tx.insert(counterparties).values({organizationId:user.organizationId,name:input.name,kind:input.kind,inn:input.inn,contact:input.contact}).returning(); await audit(tx,user,req,'create','counterparty',row.id,null,row); return row; }
      if (resource === 'contracts') { const [row] = await tx.insert(contracts).values({organizationId:user.organizationId,number:input.number,projectId:input.projectId||null,counterpartyId:input.counterpartyId,kind:input.kind,amount:String(input.amount),signedAt:input.signedAt||null}).returning(); await audit(tx,user,req,'create','contract',row.id,null,row); return row; }
      if (resource === 'purchases') { const [m] = await tx.select().from(materials).where(and(eq(materials.id,input.materialId),eq(materials.organizationId,user.organizationId))); if(!m) throw new Error('Материал не найден'); const [row] = await tx.insert(purchases).values({organizationId:user.organizationId,projectId:input.projectId,materialId:input.materialId,warehouseId:input.warehouseId||null,supplierId:input.supplierId||null,number:`ЗК-${Date.now().toString(36).toUpperCase()}`,quantity:String(input.quantity),unitPrice:String(input.unitPrice),dueAt:input.dueAt||null,note:input.note,status:'requested'}).returning(); await tx.insert(approvals).values({organizationId:user.organizationId,entityType:'purchase',entityId:row.id,assignedRole:'director'}); await audit(tx,user,req,'create','purchase',row.id,null,row); return row; }
      if (resource === 'approvals') { const [p] = await tx.select().from(purchases).where(and(eq(purchases.id,input.purchaseId),eq(purchases.organizationId,user.organizationId))); if(!p) throw new Error('Заявка не найдена'); const [a] = await tx.select().from(approvals).where(and(eq(approvals.entityId,p.id),eq(approvals.status,'pending'))); if(!a) throw new Error('Нет ожидающего согласования'); const status = input.decision === 'approve'?'ordered':input.decision === 'reject'?'rejected':'requested'; const [row] = await tx.update(purchases).set({status}).where(eq(purchases.id,p.id)).returning(); await tx.update(approvals).set({status:input.decision==='approve'?'approved':input.decision,comment:input.comment,decidedBy:user.id,decidedAt:new Date()}).where(eq(approvals.id,a.id)); await audit(tx,user,req,input.decision,'purchase',row.id,p,row); return row; }
      if (resource === 'receive') { const [p] = await tx.select().from(purchases).where(and(eq(purchases.id,input.purchaseId),eq(purchases.organizationId,user.organizationId))); if(!p || !['ordered','partial'].includes(p.status)) throw new Error('Для приемки нужен согласованный заказ'); const warehouseId = input.warehouseId || p.warehouseId; if(!warehouseId) throw new Error('Выберите склад'); const [w] = await tx.select().from(warehouses).where(and(eq(warehouses.id,warehouseId),eq(warehouses.organizationId,user.organizationId))); if(!w) throw new Error('Склад не найден'); if(Number(p.receivedQuantity)+input.quantity>Number(p.quantity)) throw new Error(`Нельзя принять больше заказа: осталось ${Number(p.quantity)-Number(p.receivedQuantity)}`); const [movement] = await tx.insert(stockMovements).values({materialId:p.materialId,warehouseId,projectId:p.projectId,purchaseId:p.id,type:'receipt',quantity:String(input.quantity),note:`Приемка ${p.number}`}).returning(); const received = Number(p.receivedQuantity)+input.quantity; await tx.update(purchases).set({receivedQuantity:String(received),status:received===Number(p.quantity)?'received':'partial'}).where(eq(purchases.id,p.id)); await audit(tx,user,req,'receive','purchase',p.id,p,{receivedQuantity:received,movementId:movement.id}); return movement; }
      if (resource === 'movements') { const [m] = await tx.select().from(materials).where(and(eq(materials.id,input.materialId),eq(materials.organizationId,user.organizationId))); const [w] = await tx.select().from(warehouses).where(and(eq(warehouses.id,input.warehouseId),eq(warehouses.organizationId,user.organizationId))); if(!m || !w) throw new Error('Материал или склад не найден'); await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${input.materialId + input.warehouseId}))`); const [balance] = await tx.select({total:sql<string>`coalesce(sum(case when ${stockMovements.type} in ('receipt','return','transfer_in') then ${stockMovements.quantity} else -${stockMovements.quantity} end),0)`}).from(stockMovements).where(and(eq(stockMovements.materialId,input.materialId),eq(stockMovements.warehouseId,input.warehouseId))); if(['issue','writeoff'].includes(input.type) && Number(balance.total)<input.quantity) throw new Error(`Невозможно списать ${input.quantity} ${m.unit} материала «${m.name}»: доступно только ${balance.total} ${m.unit}.`); const [row] = await tx.insert(stockMovements).values({materialId:input.materialId,warehouseId:input.warehouseId,projectId:input.projectId||w.projectId,taskId:input.taskId||null,type:input.type,quantity:String(input.quantity),note:input.note}).returning(); await audit(tx,user,req,input.type,'stock_movement',row.id,null,row); if(['issue','writeoff'].includes(input.type) && w.projectId) { const units = BigInt(String(input.quantity).replace('.','').padEnd((String(input.quantity).split('.')[0]?.length || 0) + 3, '0')); const priceParts = String(m.price).split('.'); const priceCents = BigInt(priceParts[0])*BigInt(100)+BigInt((priceParts[1]||'').padEnd(2,'0').slice(0,2)); const cents = units*priceCents/BigInt(1000); const cost = `${cents/BigInt(100)}.${String(cents%BigInt(100)).padStart(2,'0')}`; await tx.insert(expenses).values({projectId:input.projectId||w.projectId,taskId:input.taskId||null,category:'Материалы',description:`Списание: ${m.name} · ${input.quantity} ${m.unit}`,amount:cost,incurredAt:new Date().toISOString().slice(0,10)}); } if(Number(balance.total)+(input.type==='receipt'||input.type==='return'?input.quantity:-input.quantity)<Number(m.minStock)) await tx.insert(notifications).values({userId:user.id,title:'Низкий остаток материала',body:m.name,href:'/warehouse'}); return row; }
      throw new Error('Неизвестная операция');
    });
    return Response.json({data:result},{status:201});
  } catch(e) { if(e instanceof ZodError) return error('Проверьте поля формы: '+e.issues.map(i=>i.path.join('.')).join(', '),422); return error(e instanceof Error ? e.message : 'Ошибка операции',400); }
}
